
services:
  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "18761:8761"
    networks:
      - microservices-net

  api-gateway-cloud:
    build:
      context: ./api-gateway-cloud
      dockerfile: Dockerfile
    ports:
      - "18989:8989"
    depends_on:
      - discovery-server
    networks:
      - microservices-net

  patient:
    build:
      context: ./patient
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      - discovery-server
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=nabil

  doctor:
    build:
      context: ./doctor
      dockerfile: Dockerfile
    ports:
      - "18081:8081"
    depends_on:
      - discovery-server
      - doctor-db
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=nabil
      - SPRING_DATASOURCE_URL=jdbc:postgresql://doctor-db:5432/doctor_db
      - SPRING_DATASOURCE_USERNAME=doctor_user
      - SPRING_DATASOURCE_PASSWORD=doctor_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # o validate/create/drop-create
      - SPRING_JPA_SHOW_SQL=true

  medical-record:
    build:
      context: ./medicalRecord
      dockerfile: Dockerfile
    image: healthcare_microservices-medicalrecord
    ports:
      - "18085:8085"
    depends_on:
      - discovery-server
    networks:
      - microservices-net

  appuntamento:
    build:
      context: ./appuntamento
      dockerfile: Dockerfile
    ports:
      - "18084:8084"
    depends_on:
      - discovery-server
    networks:
      - microservices-net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge



#####################DATABASE########################
doctor-db:
  image: postgres:15
  container_name: doctor-db
  environment:
    POSTGRES_DB: doctor_db
    POSTGRES_USER: doctor_user
    POSTGRES_PASSWORD: doctor_pass
  ports:
    - "5433:5432"  # Espone la porta 5432 del container sulla 5433 del tuo host (opzionale)
  networks:
    - microservices-net
  volumes:
    - doctor-db-data:/var/lib/postgresql/data