spring.application.name=MedicalRecord

# Porta su cui gira l'app
server.port=8085

# MongoDB: URL del database
spring.data.mongodb.uri=mongodb://localhost:27017/MedicalRecord

# Abilita logging delle query Mongo (opzionale, utile per debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO