spring.application.name=Doctor

spring.datasource.url=jdbc:postgresql://localhost:5432/doctor
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
server.port=8081

##eureka-server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#actuator questi path  e una dipendenza e basta per configurare actuator e per vederlo andare sul browser e mettere :http://localhost:<porta della classe>/actuator/health
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always