spring.application.name=appuntamento

# Porta su cui gira l'app
server.port=8084

# MongoDB: URL del database
spring.data.mongodb.uri=mongodb://localhost:27017/appuntamento

# Abilita logging delle query Mongo (opzionale, utile per debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO
