spring.application.name=appuntamento

# Porta su cui gira l'app
server.port=8084

# MongoDB: URL del database
spring.data.mongodb.uri=mongodb://localhost:27017/appuntamento
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/


# Abilita logging delle query Mongo (opzionale, utile per debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

#actuator questi path  e una dipendenza e basta per configurare actuator e per vederlo andare sul browser e mettere :http://localhost:<porta della classe>/actuator/health

spring.zipkin.base-url=http://zipkin:9411
spring.sleuth.sampler.probability=1.0

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


